version: '2'

volumes:
  db:
  nextcloud:

services:
  db:
    image: mariadb
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=PASS
      - MYSQL_PASSWORD=PASS
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: always

  nextcloud:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
